import YAML from 'yaml';
import { z } from 'zod';
import { StoreError } from './errors.js';

export const RUN_KEY = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;

export const RunRecordSchema = z.strictObject({
  type: z.literal('stage-run'),
  jira_key: z.string(),
  stage_folder: z.string(),
  stage_id: z.string(),
  version: z.string().regex(/^v[1-9]\d*$/),
  run_key: z.string().regex(RUN_KEY),
  tool: z.string().min(1),
  packet_sha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
  started_at: z.iso.datetime(),
});
export type RunRecord = z.infer<typeof RunRecordSchema>;

export function renderRunRecord(record: RunRecord): string {
  const front = YAML.stringify(RunRecordSchema.parse(record), { lineWidth: 0 });
  return `---\n${front}---\n\n# ${record.jira_key} · ${record.stage_id} · ${record.version}\n\nGenerated by task-packet-store. Do not edit.\n`;
}

export function parseRunRecord(text: string): RunRecord {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!match) throw new StoreError('STORE_RUN_MISSING', 'run.md has no frontmatter');
  const parsed = RunRecordSchema.safeParse(YAML.parse(match[1]));
  if (!parsed.success) {
    const detail = parsed.error.issues.map((issue) => issue.message).join('; ');
    throw new StoreError('STORE_RUN_MISSING', `run.md frontmatter is invalid: ${detail}`);
  }
  return parsed.data;
}

const SnapshotSummary = z.strictObject({
  reason: z.string(),
  inventorySha256: z.string(),
  checkpointAt: z.string(),
});

export const RunStateSchema = z.strictObject({
  schemaVersion: z.literal(1),
  storeFile: z.string(),
  ticket: z.string(),
  stage: z.string(),
  version: z.string(),
  runKey: z.string(),
  runDirectory: z.string(),
  createdAt: z.string(),
  latestSnapshot: SnapshotSummary.nullable(),
});
export type RunState = z.infer<typeof RunStateSchema>;

export const SnapshotSchema = z.strictObject({
  schemaVersion: z.literal(1),
  reason: z.string(),
  checkpointAt: z.string(),
  fileCount: z.number().int(),
  inventorySha256: z.string(),
  files: z.array(
    z.strictObject({
      path: z.string(),
      size: z.number().int(),
      sha256: z.string(),
    }),
  ),
});
export type Snapshot = z.infer<typeof SnapshotSchema>;
